title: Sheng's Homepage
description: Sheng Yue, Associate Professor at Sun Yat-sen University
url: https://shaunyue.github.io
theme: null

author:
  name: Sheng Yue (岳晟)
  bio: Associate Professor
  employer: Sun Yat-sen University
  location: Shenzhen, China
  email: shaun.yue@hotmail.com
  googlescholar: https://scholar.google.com/citations?user=Mc_MN_MAAAAJ&hl=en&oi=ao
  orcid: https://orcid.org/0009-0001-3416-8181
  chinese_homepage: https://scst.sysu.edu.cn/teacher/YueSheng

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
